### ISSUE TITLE
Change layer "Business" -> "Services"

### ISSUE THREAD

**Issue by duderdice** [matrixps/MariosPizzerias#30]
Please change layer "Business" to "Services"; now that this layer is clearly understood for what role it plays in the application, changing to "Services" will better position us for a move to WebAPI project down the road.

**Comment by MrHydeout** [comment]
'Business' layer has been changed to 'Services'

**Comment by MrHydeout** [comment]
Got issue correctly fixed. Changed "Business" => "Services"
