### ISSUE TITLE
Implement Repository pattern

### ISSUE THREAD

**Issue by duderdice** [matrixps/MariosPizzerias#31]
Please implement a Repository pattern to follow best architectural practices.  I have a included a link below to an article which discusses this issue:

[Add a Repository Class ](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api#add-a-repository-class)

NOTE - Please make sure that you read the article and understand the concepts, and avoid implementing any changes which are not applicable, as the article is focused on implementing a WebAPI application, which is a little different than what we have at the moment.

**Comment by MrHydeout** [comment]
Implemented repository pattern in order to aid in database access and data transfer. See : commit 909ed84088f4f79e2d3edc1331dec505de215019
