### ISSUE TITLE
Implement one or two select JSON calls

### ISSUE THREAD

**Issue by duderdice** [matrixps/MariosPizzerias#32]
Let's implement one or two JSON calls in the front-end views, where best applicable, so we can see how that would look and work.  I'll leave it to your discretion to choose where is the best place to do so.

**Comment by MrHydeout** [comment]
Implemented JSON call on the 'CreatePizza' page for the toppings checkbox icons. See : commit 8864857a16fb47b1f0b32b62e5417137928ea838
