### ISSUE TITLE
Change folder "DTOs" -> "Models"

### ISSUE THREAD

**Issue by duderdice** [matrixps/MariosPizzerias#33]
Now that we have a clear understanding of DTOs (Data Transfer Objects!), let's rename this folder to "Models".  These are often synonymous (although not always), and this is the "M" in M-V-C, as the models are the object that the front-end would get from the backend (busines/services layer) which represent or model the key business concepts.

**Comment by MrHydeout** [comment]
Changed DTOs (located under Services) to Models. See Commit :  b9ea34adad0cd5d6a756211d7fe02d514a8d39bf
