### ISSUE TITLE
Sample data is included in Initialize_data.sql script

### ISSUE THREAD

**Issue by duderdice** [matrixps/MariosPizzerias#37]
After deploying the app, there is invalid data in my Orders table; this table should be empty upon initial deployment, and only populated when customers submit orders.  If sample data is desired for the short-term development purposes, these should be handled by a separate script in order to maintain separation of concerns.

**Comment by MrHydeout** [comment]
Moved unnecessary data from "Initialize_Data.sql" to a newly created "Sample_Data.sql". Orders table is now initially empty, and will not be populated until orders begin being added.  "Sample_Data.sql" is for testing purposes only. See : commit 224b608cacd1af688a6ddd6281cf74ab85dd257b
